#!/bin/bash

pkg install python -y
pip install requests
pip install timedelta
pip install bs4


echo alias test=\"python \~/fenix-test_solver/main.py\" > ~/.bashrc
echo alias cls=\"clear\" >> ~/.bashrc
echo cd \~/fenix-test_solver >> ~/.bashrc
echo cls >> ~/.bashrc
echo test >> ~/.bashrc

echo
echo Установка завершена успешно!
echo При запуске приложения или новой вкладки скрипт будет запускаться сам
echo Также его запускает команда "test" в терминале
exit
