#!/bin/bash

pkg install python -y
pip install requests
pip install timedelta
pip install bs4


echo alias test=\"python fenix-test_solver/main.py\" > .bashrc
echo alias cls=\"clear\" >> .bashrc
echo cls >> .bashrc
echo test >> .bashrc
exit
